### ISSUE TITLE
v3.9.0 - Error in "Workflow consistency" module.

### ISSUE THREAD

**Issue by pnmcosta** [Kentico/KInspector#301]
### Brief bug description

Error in "Workflow consistency" module. Error message: Root element is missing.

### Repro steps

1. Go to 'Analysis'
2. Click on 'Load the module' of '[General] Workflow consistency'
3. Scroll up to top

### Expected behavior

Should show the report's analysis

### Test environment

 - Platform/OS: Windows 10, Kentico 11 Web Site 
 - Browser Chrome
 - Version 3.9.0

### Additional context

All other modules work as expected, the same instance has 2 sites, one is Portal Engine the other MVC, and both are configured with a Root node and work fine. Let me know if you need any more info?

**Comment by ChristopherJennings** [comment]
Hi @pnmcosta, thanks for the issue. We've been working on V4 for a while and just this week released an alpha version of it. This module is one of the modules that we've already ported over to V4. Could you try this module in V4 and let us know if you get the same results? We made a lot of changes to this module in porting it over to address a number of issues. 

We're not planning to update version 3 any longer, so please let us know if this happens in the latest V4 alpha. If it doesn't, I'd love to connect to investigate the issue further so we can resolve it. 

Thanks!

**Comment by ChristopherJennings** [comment]
Forgot to mention that this was merged with the document consistency issues and the new report name is "Content Tree Consistency Analysis".

**Comment by pnmcosta** [comment]
Hi @ChristopherJennings thanks so much for the update. I will run v4 instead, I opted for using v3.9.0 before cause I wasn't sure what reports had/not been migrated. Do you have a list?

Thanks so much.

**Comment by pnmcosta** [comment]
Hi @ChristopherJennings don't want to raise a new issue if it's a known one, when I try to run the latest release I get:

```
Hosting environment: Production
Content root path: C:\Tools\Kentico.Inspector.4.0.0-alpha.3
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLOQ9SDTNFRE", Request id "0HLOQ9SDTNFRE:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
If not, do you want me to raise a new issue for this? I'm going to try the dev mode from the repo instead now.

**Comment by pnmcosta** [comment]
I believe I have all the requirements in place, but to be honest I'm new to Core, so am not sure if I'm doing something wrong! 

I correctly setup a clone of the repo, but am having the same error when running on both console or IIS express mode, and I did do a `npm run build` to the ClientApp as instructed in the readme.

However please note to have a build of the solution actually working, I did have to add the following nuget package:
![image](https://user-images.githubusercontent.com/550684/62529566-c9821100-b836-11e9-9177-360aec77034b.png)

**Comment by ChristopherJennings** [comment]
We weren't aware that the latest alpha build wasn't loading the front-end properly. I've created an issue (#302) to look into this.

Regarding the additional package, we've seen the before, but chalked it up to one developer's machine (others didn't have the issue). I took a look and it appears to be an issue with the library being referenced via a hintpath rather than nuget. There's another issue for that: #303.

Alpha bugs aside, how's the new version working for you? Does the new version of this report work for you?

**Comment by pnmcosta** [comment]
Hi @ChristopherJennings thanks for the update, I'll have to wait for the new tickets cause I was literally unable to get it going, so I can't really provide any sort of feedback :/

Shall I be using a previous alpha version?

**Comment by ChristopherJennings** [comment]
I've just confirmed that download for alpha.2 runs on my machine whereas alpha.3 gave the same issue as you reported. You can try that for now. 

A few questions for trying to run from source:
1. What's the output of `npm run build`? 
1. After running `npm run build`, what do you see in the `KenticoInspector.WebApplication/ClientApp/dist` folder? 
1. Do you have the Vue CLI installed?

**Comment by ChristopherJennings** [comment]
Just a note, we fixed the release in [v4.0.0-alpha.4](https://github.com/Kentico/KInspector/releases/tag/v4.0.0-alpha.4). Also, we added the SQLClient dependency you mentioned as well.

**Comment by pnmcosta** [comment]
Thanks @ChristopherJennings umm I suspect it might have been the Vue CLI as I built the front end on WSL. I will try the new release and code from the repo, and will let you know. You can close this ticket for now if you'd like. Thanks.

**Comment by pnmcosta** [comment]
Hi @ChristopherJennings, managed to get the release working (not the repo clone) however, whatever I don't get any reports to run, the connection seems to have worked, at least is saves and I can get back to it, but always get the following:

![image](https://user-images.githubusercontent.com/550684/62613800-1b439d80-b902-11e9-9d2b-a149eea02da3.png)

It's as if the reports are not loading, and there's nothing on the console. I'm going to give the repo clone a go next.

Thanks,
P.

**Comment by pnmcosta** [comment]
Actually sorry, I didn't notice before, there's some errors on the console:

```
Newtonsoft.Json.JsonSerializationException: Error getting value from 'Metadata' on 'KenticoInspector.Reports.WebPartPerformanceAnalysis.Report'. ---> System.IO.FileNotFoundException: Could not find file 'C:\Tools\Kentico.Inspector.4.0.0-alpha.4\WebPartPerformanceAnalysis\Metadata\en-GB.yaml'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at KenticoInspector.Core.Helpers.ReportMetadataService.DeserializeYaml[T](String path) in C:\projects\kinspector-98xj0\KenticoInspector.Infrastructure\Services\ReportMetadataService.cs:line 22
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLOR3BKNFTK3", Request id "0HLOR3BKNFTK3:00000005": An unhandled exception was thrown by the application.
```

**Comment by ChristopherJennings** [comment]
Ah, the issue there is our fancy new metadata is designed for multi-lingual, but is only translated into en-US at the moment. Additionally, we didn't add a fallback mechanism. I've opened a new issue for that and hopefully we'll resolve that soon. In the meantime, you should be able to get the reports to load by renaming all `en-US.yaml` files to `en-GB.yaml`

**Comment by pnmcosta** [comment]
Kewl, no worries, I'll just wait for patched release/update to the main repo. Thanks for all your help, I'll just close this ticket now :D

**Comment by ChristopherJennings** [comment]
@pnmcosta just want to let you know that [v4.0.0-alpha.5](https://github.com/Kentico/KInspector/releases/tag/v4.0.0-alpha.5) should address the culture issue. Thanks for your patience and persistence!
