### ISSUE TITLE
System.Net.WebException when running "[General] Cache items" check

### ISSUE THREAD

**Issue by jamesbloor** [Kentico/KInspector#57]
Trying to run the [General] Cache items returns the following error for any project:

System.Net.WebException: The remote server returned an error: (404) Not Found.
 at System.Net.HttpWebRequest.GetResponse()
 at Kentico.KInspector.Modules.CacheItemsModule.GetResults(InstanceInfo instanceInfo) in C:\projects\kinspector\KInspector.Modules\Modules\General\CacheItemsModule.cs:line 34

![capture](https://cloud.githubusercontent.com/assets/6383250/11810121/aff97a10-a323-11e5-9b3e-f268608a3e11.PNG)

**Comment by ondrejsevcik** [comment]
Hi James,

what was the url you've entered into the form?

**Comment by petrsvihlik** [comment]
seems to work fine
